[tool.poetry]
name = "git-auto-merge"
version = "1.2.1"
description = ""
authors = ["Clint M <cmodien@gmail.com>"]
readme = "README.md"

[tool.black]
line_length = 100

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.11"
packaging = "^23.1"
loguru = "^0.7.0"
jsonpickle = "^3.0.1"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pyright = "^1.1.313"
pytest-snapshot = "^0.9.0"

[tool.poetry.scripts]
git-auto-merge = "git_auto_merge:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
