[tool.poetry]
name = "git-auto-merge"
version = "1.3.7"
description = ""
authors = ["Clint M <cmodien@gmail.com>"]
readme = "README.md"

[tool.black]
line_length = 100

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
click = "^8.1.6"
jsonpickle = "^3.0.1"
loguru = "^0.7.0"
packaging = "^21"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
pylint = "*"
pyright = "^1.1.313"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-snapshot = "^0.9.0"
safety = "*"

[tool.poetry.scripts]
git-auto-merge = "git_auto_merge:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
