[tool.poetry]
name = "gitflow-merge"
version = "0.1.0"
description = ""
authors = ["Clint M <cmodien@gmail.com>"]
readme = "README.md"

[tool.black]
line_length = 100

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pyright = "^1.1.313"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
